# # Static states for different conversation handlers
# REG_START, REG_NAME, REG_EMAIL, REG_PHONE, REG_CONFIRM = range(5)
# BOOK_START, BOOK_DATE, BOOK_ROOM, BOOK_GUESTS, BOOK_CONFIRM = range(5, 10)
# MNG_START, MNG_OPTION, MNG_CONFIRM = range(10, 13)

REG_REDIRECT, REG_SINGPASS, REG_NAME, REG_EMAIL, REG_PHONE, REG_REMARKS, REG_CONFIRM, REG_EDIT = range(8)
BOOKING_DATE_TIME, BOOKING_CONFIRM, BOOKING_REMARKS, BOOKING_END = range(8, 12)
# SURVEY_START, SURVEY