# # Static states for different conversation handlers

REG_REDIRECT, REG_SINGPASS, REG_NAME, REG_EMAIL, REG_PHONE, REG_REMARKS, REG_CONFIRM, REG_EDIT = range(8)
BOOKING_DATE_TIME, BOOKING_CONFIRM, BOOKING_REMARKS, BOOKING_END = range(8, 12)
POST_SURVEY_DOC, POST_SURVEY_SYMPTOMS, POST_SURVEY_SYMPTOMS_REMARKS, POST_SURVEY_MED, POST_SURVEY_REMINDER, POST_SURVEY_FOLLOWUP, POST_SURVEY_RATING, POST_SURVEY_FEEDBACK = range(12, 20)
